name: Deploy to VPS

on:
  push:
    branches: [ "3.x" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
              cd /var/www/vito
              sudo git pull origin 3.x
              sudo php8.4 /usr/local/bin/composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
              sudo php8.4 artisan migrate --force
              sudo npm install
              sudo npm run build
              sudo php8.4 artisan optimize
              sudo php8.4 artisan horizon:terminate
